name: iconify
description: A new Flutter project.

version: 1.0.0+2

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  icons_plus: ^3.0.0
  nb_utils: ^2.0.9
  google_fonts: ^4.0.3
  flutter_highlight: ^0.7.0
  font_awesome_flutter: ^10.4.0
  line_icons: ^2.0.1
  ionicons: ^0.2.2
  eva_icons_flutter: ^3.1.0
  fluentui_system_icons: ^1.1.190
  carbon_icons: ^0.0.1+2
  lucide_icons: ^0.115.0
  heroicons: ^0.7.0
  phosphor_flutter: ^1.4.0
  unicons: ^2.1.0
  flutter_iconly: ^1.0.2
  iconsax: ^0.0.8
  material_design_icons_flutter: ^6.0.7096
  get: ^4.6.5
  objectdb: ^1.2.1+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  fluttertoast: ^6.0.1
  launch_review: ^3.0.1
  url_launcher: ^6.1.10
  share_plus: ^6.3.1
  package_info_plus: ^3.0.3
  google_mobile_ads: ^2.3.0
  shared_preferences: ^2.0.18
  flutter_widget_from_html: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  build_runner: ^2.3.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
